manage signed timestamped values
Luos-io/LuosHAL pull request #39
Opened 2022-02-02 16:06 UTC by ncros3

﻿# Comments for current PR
* *add your comments here*
* ...
 

<br><br />
<br><br />
               *!!! WARNING : DO NOT EDIT THE CHECKLIST BELOW !!!*
# Checklist : Merge from DEVELOP branch
## Code Quality
- [ ] Each function has a header (description, inputs, outputs) 
- [ ] Code is commented (particularly in hard to understand areas)
- [ ] There are no new warnings that can be corrected
- [ ] Commits policy is respected (constitancy commits, clear commits comments)
<br><br />
## Tests Review
- [ ]  Manual Tests for new features have been *reviewed*
- [ ]  Automatic Tests for new features have been *reviewed*
<br><br />
## Tests are passed the best as I can
- [ ]  Non regression existing tests are *passed OK*
- [ ]  New tests for new features & bug fixes are *passed OK*
<br><br />
## Documentation
- [ ] Documentation is up to date
- [ ] Changelog for next release is up-to-date : [fill here](https://github.com/Luos-io/Luos/pull/115)
- [ ] If needed, tests are briefly described in [test repository](https://github.com/Luos-io/tests)

2022-02-02 19:01 UTC, nicolas-rabault requested changes
I spotted some things I don't get.
I think my comments are more related to the basic timestamp feature...

2022-02-02 19:01 UTC, nicolas-rabault commented on ATSAMD21/luos_hal.h
> -    uint64_t higher_timestamp;
Why do we need those as global variables?
As I see it we just use them in the LuosHAL_GetTimestamp function to compute the returned Timestamp value.

2022-02-02 19:01 UTC, nicolas-rabault commented on ATSAMD21/luos_hal.h
> +    uint32_t start_offset;
Why do we have to save an offset? Is there any case where we would want to reset the timestamp?
This could break the timeline continuity and lead to event date loss.
Did I miss something?

2022-02-02 19:01 UTC, nicolas-rabault commented on ATSAMD21/luos_hal.h
> +int64_t LuosHAL_GetTimestamp(void);
The returned timestamp is a date, So I don't see any reason to make it signed.
Is there any case where the returned value could be negative?

2022-02-03 10:22 UTC, ncros3 commented
We don't need to use int64_t so I changed my PR. 

After reading your comments, I think we should put this feature on hold for a moment. This feature is tighly coupled with our tools as the Saas tool. I think we should wait for this feature to have a clear view of what we need to do.

2022-03-04 08:57 UTC, ncros3 commented on ATSAMD21/luos_hal.h
> +    uint32_t start_offset;
That was a requirement to reset the timestamp.

2022-03-15 09:46 UTC, nicolas-rabault commented on ATSAMD21/luos_hal.h
> +    uint32_t start_offset;
ok

2022-03-15 10:02 UTC, nicolas-rabault approved these changes
I'm ok with it But I think we should move most of the timestamp function to Luos.
I describe it on this issue: https://github.com/Luos-io/Luos/issues/164

2022-03-21 13:36 UTC, Salem-Luos approved these changes

2022-03-22 11:37 UTC, merged